enum ExpenseCategory {
	Food = "Food",
	Housing = "Housing",
	Transportation = "Transportation",
	Utilities = "Utilities",
	Health = "Health",
	Insurance = "Insurance",
	Entertainment = "Entertainment",
	Clothing = "Clothing",
	PersonalCare = "Personal Care",
	Education = "Education",
	Travel = "Travel",
	Gifts = "Gifts",
	Donations = "Donations",
	Groceries = "Groceries",
	DiningOut = "Dining Out",
	Subscriptions = "Subscriptions",
	HomeMaintenance = "Home Maintenance",
	Childcare = "Childcare",
	Pets = "Pets",
	Fitness = "Fitness",
	Hobbies = "Hobbies",
	OfficeSupplies = "Office Supplies",
	Technology = "Technology",
	Savings = "Savings",
	Investments = "Investments",
	Taxes = "Taxes",
	Repairs = "Repairs",
	Events = "Events",
	Miscellaneous = "Miscellaneous",
	DebtRepayment = "Debt Repayment",
}

export default ExpenseCategory;
